name: Continuous Deployment

# Trigger this workflow only if the CI workflow is successful
on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed
    branches:
      - main

jobs:
   deploy:
     runs-on: ubuntu-latest

     steps:
     

      # Download the artifact from the CI workflow
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      # Add your deployment commands here
      - name: Deploy
        run: echo "Running deployment commands"
